server:
  image: tofuliang/docker-shadowsocks-libev
  ports:
    - "23493:23493/tcp"
    - "23493:23493/udp"
    - "33493:33493/tcp"
    - "33493:33493/udp"
    - "22:22/tcp"
  environment:
#    - SS_SERVER_ADDR=0.0.0.0
    - SS_SERVER_PORT=23493
#    - SS_METHOD=aes-256-cfb
    - SS_PASSWORD=247KuvJYXm9v
#    - SS_TIMEOUT=60
#    - DNS_ADDR=8.8.8.8
#    - SS_OPTIONS=
    - KCP_SERVER_PORT=33493
    - KCP_CRYPT=salsa20
#    - KCP_MTU=1350
#    - KCP_MODE=fast
    - KCP_DSCP=0
    - "KCP_OPTIONS=--key 2TBltAzll6hx --nocomp --sndwnd 512 --rcvwnd 512 --datashard 5 --parityshard 5"
    - SSH_PASS=toor
  command: /usr/local/bin/server.sh
  restart: always
client:
  image: tofuliang/docker-shadowsocks-libev
  ports:
    - "1080:1080/tcp"
    - "1080:1080/udp"
    - "7777:7777/tcp"
    - "33493:33493/tcp"
    - "33493:33493/udp"
  environment:
    - TERM=xterm
    - KCP_LOCAL_PORT=33493
#    - KCP_SERVER_ADDR=1.2.3.4
#    - KCP_SERVER_PORT=31214
    - KCP_CRYPT=salsa20
    - KCP_MTU=512
#    - KCP_MODE=fast
    - KCP_DSCP=0
    - "KCP_OPTIONS=--key 2TBltAzll6hx --nocomp --sndwnd 512 --rcvwnd 512 --datashard 5 --parityshard 5"
    - SS_LOCAL_PORT=1080
    - SS_PASSWORD=247KuvJYXm9v
#    - SS_METHOD=aes-256-cfb
#    - SS_TIMEOUT=60
#    - SS_LOCAL_ADDR=0.0.0.0
#    - SS_OPTIONS=
#    - COW_LOCAL_ADDR=0.0.0.0
#    - COW_LOCAL_PORT=7777
  command: /usr/local/bin/client.sh
  restart: always

