server:
  image: tofuliang/docker-shadowsocks-libev
  ports:
    - "23493:23493/tcp" #ss-server
    - "23493:23493/udp" #ss-server
    - "33493:33493/udp" #kcp-server
  environment:
#    - SS_SERVER_ADDR=0.0.0.0
    - SS_SERVER_PORT=23493
#    - SS_METHOD=aes-256-cfb
    - SS_PASSWORD=247KuvJYXm9v
#    - SS_TIMEOUT=60
#    - DNS_ADDR=8.8.8.8
#    - SS_OPTIONS=
    - KCP_SERVER_PORT=33493
    - KCP_CRYPT=salsa20
    - KCP_MTU=512
#    - KCP_MODE=fast
    - KCP_DSCP=0
    - "KCP_OPTIONS=--key 2TBltAzll6hx --nocomp --sndwnd 512 --rcvwnd 512 --datashard 5 --parityshard 5"
  command: /usr/local/bin/server.sh
  restart: always
client:
  image: tofuliang/docker-shadowsocks-libev:arukas
  ports:
    - "1082:1082/tcp" #ss-local
    - "1082:1082/udp" #ss-local
    - "7777:7777/tcp" #cow-client
    - "33493:33493/tcp" #kcp-client
  environment:
    - TERM=xterm
    - KCP_LOCAL_PORT=33493
#    - KCP_SERVER_ADDR=1.2.3.4
#    - KCP_SERVER_PORT=31214
    - KCP_CRYPT=salsa20
    - KCP_MTU=512
#    - KCP_MODE=fast
    - KCP_DSCP=0
    - "KCP_OPTIONS=--key 2TBltAzll6hx --nocomp --sndwnd 512 --rcvwnd 512 --datashard 5 --parityshard 5"
    - SS_LOCAL_PORT=1082
    - SS_PASSWORD=247KuvJYXm9v
#    - SS_METHOD=aes-256-cfb
#    - SS_TIMEOUT=60
#    - SS_LOCAL_ADDR=0.0.0.0
#    - SS_OPTIONS=
#    - COW_LOCAL_ADDR=0.0.0.0
#    - COW_LOCAL_PORT=7777
    - ARUKAS_TOKEN=YOUR_TOKEN
    - ARUKAS_SECERT=YOUR_SECERT
    - ARUKAS_CHECK_FEQ=40
    - DEBUG=true
  command: /usr/local/bin/client.sh
  restart: always
