server:
  image: tofuliang/docker-shadowsocks-libev
  ports:
    - "23493:23493/tcp"
    - "23493:23493/udp"
    - "33493:33493/tcp"
    - "33493:33493/udp"
  environment:
#    - SS_SERVER_ADDR=0.0.0.0
    - SS_SERVER_PORT=23493
#    - SS_METHOD=aes-256-cfb
    - SS_PASSWORD=247KuvJYXm9v
#    - SS_TIMEOUT=60
#    - DNS_ADDR=8.8.8.8
#    - SS_OPTIONS=
    - KCP_SERVER_PORT=33493
    - KCP_CRYPT=none
#    - KCP_MTU=1350
#    - KCP_MODE=fast
    - KCP_DSCP=46
    - "KCP_OPTIONS=--key 2TBltAzll6hx --nocomp --sndwnd 1024"
  command: /usr/local/bin/server.sh
  restart: always
client:
  image: tofuliang/docker-shadowsocks-libev:arukas
  ports:
    - "1082:1082/tcp"
    - "1082:1082/udp"
    - "33493:33493/tcp"
    - "33493:33493/udp"
  environment:
    - TERM=xterm
    - KCP_LOCAL_PORT=33493
#    - KCP_SERVER_ADDR=1.2.3.4
#    - KCP_SERVER_PORT=31214
    - KCP_CRYPT=none
#    - KCP_MTU=1350
#    - KCP_MODE=fast
    - KCP_DSCP=46
    - "KCP_OPTIONS=--key 2TBltAzll6hx --nocomp --sndwnd 1024"
    - SS_LOCAL_PORT=1082
    - SS_PASSWORD=247KuvJYXm9v
#    - SS_METHOD=aes-256-cfb
#    - SS_TIMEOUT=60
#    - SS_LOCAL_ADDR=0.0.0.0
#    - SS_OPTIONS=
    - ARUKAS_TOKEN=YOUR_TOKEN
    - ARUKAS_SECERT=YOUR_SECERT
    - ARUKAS_CHECK_FEQ=40
  command: /usr/local/bin/client.sh
  restart: always

